/****************************************************************************************
 *
 * File:
 * 		WindDataMsg.h
 *
 * Purpose:
 *		Contains the following data: Wind temperature, wind direction and wind speed.
 *		Commonly generated by a wind sensor
 *
 * Developer Notes:
 *
 ***************************************************************************************/

#pragma once

#include "Message.h"


class WindDataMsg : public Message {
public:
	WindDataMsg(NodeID destinationID, NodeID sourceID, uint8_t windDir, uint8_t windSpeed, uint16_t windTemp)
		:Message(MessageType::WindData, sourceID, destinationID),
		m_windDir(windDir), m_windSpeed(windSpeed), m_windTemp(windTemp)
	{ }

	WindDataMsg(uint8_t windDir, uint8_t windSpeed, uint16_t windTemp)
		:Message(MessageType::WindData, NodeID::None, NodeID::None),
		m_windDir(windDir), m_windSpeed(windSpeed), m_windTemp(windTemp)
	{ }

	virtual ~WindDataMsg() { }

	uint8_t windDirection() { return m_windDir; }
	uint8_t windSpeed() { return m_windSpeed; }
	uint16_t windTemp() { return m_windTemp; }

private:
	uint8_t 	m_windDir;
	uint8_t 	m_windSpeed;
	uint16_t	  m_windTemp;
};
